package net.leafenzo.squashed.item;


import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.leafenzo.squashed.Super;
import net.leafenzo.squashed.block.ModBlocks;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;



public class ModItemGroups {

    public static ItemGroup SQUASHED = Registry.register(Registries.ITEM_GROUP, new Identifier(Super.MOD_ID, "squashed"),
            FabricItemGroup.builder().displayName(Text.translatable("itemgroup.squashed"))
                    .icon(() -> new ItemStack(ModBlocks.COMPRESSED_STONE)).entries((displayContext, entries) -> {
                     entries.add(ModBlocks.BLAZE_ROD_BLOCK);
                     entries.add(ModBlocks.INK_SAC_BLOCK);
                     entries.add(ModBlocks.STICK_BLOCK);
                     entries.add(ModBlocks.FIRE_CHARGE_BLOCK);
                     entries.add(ModBlocks.MAGMA_CREAM_BLOCK);
                     entries.add(ModBlocks.BLAZE_POWDER_BLOCK);
                     entries.add(ModBlocks.RAW_SALMON_BLOCK);
                     entries.add(ModBlocks.COOKED_SALMON_BLOCK);
                     entries.add(ModBlocks.RAW_COD_BLOCK);
                     entries.add(ModBlocks.COOKED_COD_BLOCK);
                     entries.add(ModBlocks.RAW_RABBIT_BLOCK);
                     entries.add(ModBlocks.COOKED_RABBIT_BLOCK);
                     entries.add(ModBlocks.RAW_MUTTON_BLOCK);
                     entries.add(ModBlocks.COOKED_MUTTON_BLOCK);
                     entries.add(ModBlocks.RAW_CHICKEN_BLOCK);
                     entries.add(ModBlocks.COOKED_CHICKEN_BLOCK);
                     entries.add(ModBlocks.RAW_BEEF_BLOCK);
                     entries.add(ModBlocks.COOKED_BEEF_BLOCK);
                     entries.add(ModBlocks.RAW_PORK_BLOCK);
                     entries.add(ModBlocks.COOKED_PORK_BLOCK);
                     entries.add(ModBlocks.ROTTEN_FLESH_BLOCK);
                     entries.add(ModBlocks.SPIDER_EYE_BLOCK);
                     entries.add(ModBlocks.WHEAT_SEED_BLOCK);
                     entries.add(ModBlocks.PUMPKIN_SEED_BLOCK);
                     entries.add(ModBlocks.BEETROOT_SEED_BLOCK);
                     entries.add(ModBlocks.MELON_SEED_BLOCK);
                     entries.add(ModBlocks.COCOA_BEAN_BLOCK);
                     entries.add(ModBlocks.DEAD_BUSH_BLOCK);
                     entries.add(ModBlocks.GLOW_BERRIES_BLOCK);
                     entries.add(ModBlocks.SWEET_BERRIES_BLOCK);
                     entries.add(ModBlocks.GRASS_CLIPPINGS_BLOCK);
                     entries.add(ModBlocks.FERN_BLOCK);
                     entries.add(ModBlocks.GLOW_LICHEN_BLOCK);
                     entries.add(ModBlocks.PUMPKIN_PILE);
                     entries.add(ModBlocks.HAY_PILE);
                     entries.add(ModBlocks.MELON_PILE);
                     entries.add(ModBlocks.SUGARCANE_BLOCK);
                     entries.add(ModBlocks.SEA_PICKLE_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_SOUL_SAND);
                     entries.add(ModBlocks.SUPER_COMPRESSED_SOUL_SAND);
                     entries.add(ModBlocks.COMPRESSED_COBBLESTONE);
                     entries.add(ModBlocks.SUPER_COMPRESSED_COBBLESTONE);
                     entries.add(ModBlocks.COMPRESSED_STONE);
                     entries.add(ModBlocks.SUPER_COMPRESSED_STONE);
                     entries.add(ModBlocks.COMPRESSED_ANDESITE);
                     entries.add(ModBlocks.SUPER_COMPRESSED_ANDESITE);
                     entries.add(ModBlocks.COMPRESSED_GRAVEL);
                     entries.add(ModBlocks.SUPER_COMPRESSED_GRAVEL);
                     entries.add(ModBlocks.COMPRESSED_TUFF);
                     entries.add(ModBlocks.SUPER_COMPRESSED_TUFF);
                     entries.add(ModBlocks.COMPRESSED_BLACKSTONE);
                     entries.add(ModBlocks.SUPER_COMPRESSED_BLACKSTONE);
                     entries.add(ModBlocks.COMPRESSED_OBSIDIAN);
                     entries.add(ModBlocks.SUPER_COMPRESSED_OBSIDIAN);
                     entries.add(ModBlocks.COMPRESSED_DEEPSLATE);
                     entries.add(ModBlocks.SUPER_COMPRESSED_DEEPSLATE);
                     entries.add(ModBlocks.COMPRESSED_NETHERRACK);
                     entries.add(ModBlocks.SUPER_COMPRESSED_NETHERRACK);
                     entries.add(ModBlocks.COMPRESSED_END_STONE);
                     entries.add(ModBlocks.SUPER_COMPRESSED_END_STONE);
                     entries.add(ModBlocks.COMPRESSED_DIORITE);
                     entries.add(ModBlocks.SUPER_COMPRESSED_DIORITE);
                     entries.add(ModBlocks.COMPRESSED_GRANITE);
                     entries.add(ModBlocks.SUPER_COMPRESSED_GRANITE);
                     entries.add(ModBlocks.COMPRESSED_DIRT);
                     entries.add(ModBlocks.SUPER_COMPRESSED_DIRT);
                     entries.add(ModBlocks.COMPRESSED_SAND);
                     entries.add(ModBlocks.SUPER_COMPRESSED_SAND);
                     entries.add(ModBlocks.COMPRESSED_DRIPSTONE);
                     entries.add(ModBlocks.COMPRESSED_CALCITE);
                     entries.add(ModBlocks.COMPRESSED_MUD);
                     entries.add(ModBlocks.COMPRESSED_MOSS);
                     entries.add(ModBlocks.COMPRESSED_CLAY);
                     entries.add(ModBlocks.COMPRESSED_RED_SAND);
                     entries.add(ModBlocks.SUPER_COMPRESSED_RED_SAND);
                     entries.add(ModBlocks.COMPRESSED_MAGMA_BLOCK);
                     entries.add(ModBlocks.WHITE_DYE_BLOCK);
                     entries.add(ModBlocks.ORANGE_DYE_BLOCK);
                     entries.add(ModBlocks.MAGENTA_DYE_BLOCK);
                     entries.add(ModBlocks.LIGHT_BLUE_DYE_BLOCK);
                     entries.add(ModBlocks.YELLOW_DYE_BLOCK);
                     entries.add(ModBlocks.LIME_DYE_BLOCK);
                     entries.add(ModBlocks.PINK_DYE_BLOCK);
                     entries.add(ModBlocks.GRAY_DYE_BLOCK);
                     entries.add(ModBlocks.LIGHT_GRAY_DYE_BLOCK);
                     entries.add(ModBlocks.CYAN_DYE_BLOCK);
                     entries.add(ModBlocks.PURPLE_DYE_BLOCK);
                     entries.add(ModBlocks.BLUE_DYE_BLOCK);
                     entries.add(ModBlocks.BROWN_DYE_BLOCK);
                     entries.add(ModBlocks.GREEN_DYE_BLOCK);
                     entries.add(ModBlocks.RED_DYE_BLOCK);
                     entries.add(ModBlocks.BLACK_DYE_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_BASALT);
                     entries.add(ModBlocks.SUPER_COMPRESSED_BASALT);
                     entries.add(ModBlocks.WHITE_COMPRESSED_WOOL);
                     entries.add(ModBlocks.ORANGE_COMPRESSED_WOOL);
                     entries.add(ModBlocks.MAGENTA_COMPRESSED_WOOL);
                     entries.add(ModBlocks.LIGHT_BLUE_COMPRESSED_WOOL);
                     entries.add(ModBlocks.YELLOW_COMPRESSED_WOOL);
                     entries.add(ModBlocks.LIME_COMPRESSED_WOOL);
                     entries.add(ModBlocks.PINK_COMPRESSED_WOOL);
                     entries.add(ModBlocks.GRAY_COMPRESSED_WOOL);
                     entries.add(ModBlocks.LIGHT_GRAY_COMPRESSED_WOOL);
                     entries.add(ModBlocks.CYAN_COMPRESSED_WOOL);
                     entries.add(ModBlocks.PURPLE_COMPRESSED_WOOL);
                     entries.add(ModBlocks.BLUE_COMPRESSED_WOOL);
                     entries.add(ModBlocks.BROWN_COMPRESSED_WOOL);
                     entries.add(ModBlocks.GREEN_COMPRESSED_WOOL);
                     entries.add(ModBlocks.RED_COMPRESSED_WOOL);
                     entries.add(ModBlocks.BLACK_COMPRESSED_WOOL);
                     entries.add(ModBlocks.BOOK_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_OAK_LEAVES);
                     entries.add(ModBlocks.COMPRESSED_SPRUCE_LEAVES);
                     entries.add(ModBlocks.COMPRESSED_BIRCH_LEAVES);
                     entries.add(ModBlocks.COMPRESSED_JUNGLE_LEAVES);
                     entries.add(ModBlocks.COMPRESSED_ACACIA_LEAVES);
                     entries.add(ModBlocks.COMPRESSED_DARK_OAK_LEAVES);
                     entries.add(ModBlocks.COMPRESSED_MANGROVE_LEAVES);
                     entries.add(ModBlocks.COMPRESSED_AZALEA_LEAVES);
                     entries.add(ModBlocks.COMPRESSED_FLOWERING_AZALEA_LEAVES);
                     entries.add(ModBlocks.LEATHER_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_OAK_LOG);
                     entries.add(ModBlocks.COMPRESSED_SPRUCE_LOG);
                     entries.add(ModBlocks.COMPRESSED_BIRCH_LOG);
                     entries.add(ModBlocks.COMPRESSED_JUNGLE_LOG);
                     entries.add(ModBlocks.COMPRESSED_ACACIA_LOG);
                     entries.add(ModBlocks.COMPRESSED_DARK_OAK_LOG);
                     entries.add(ModBlocks.COMPRESSED_MANGROVE_LOG);
                     entries.add(ModBlocks.COMPRESSED_CRIMSON_STEM);
                     entries.add(ModBlocks.COMPRESSED_WARPED_STEM);
                     entries.add(ModBlocks.COMPRESSED_BAMBOO);
                     entries.add(ModBlocks.COMPRESSED_OAK_SAPLING);
                     entries.add(ModBlocks.COMPRESSED_SPRUCE_SAPLING);
                     entries.add(ModBlocks.COMPRESSED_BIRCH_SAPLING);
                     entries.add(ModBlocks.COMPRESSED_JUNGLE_SAPLING);
                     entries.add(ModBlocks.COMPRESSED_ACACIA_SAPLING);
                     entries.add(ModBlocks.COMPRESSED_DARK_OAK_SAPLING);
                     entries.add(ModBlocks.COMPRESSED_AZALEA_SAPLING);
                     entries.add(ModBlocks.COMPRESSED_FLOWERING_AZALEA_SAPLING);
                     entries.add(ModBlocks.COMPRESSED_MANGROVE_PROPAGULE);
                     entries.add(ModBlocks.COMPRESSED_CRIMSON_FUNGUS);
                     entries.add(ModBlocks.COMPRESSED_WARPED_FUNGUS);
                     entries.add(ModBlocks.CHORUS_FRUIT_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_SEAGRASS);
                     entries.add(ModBlocks.COMPRESSED_CACTUS);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_A);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_B);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_C);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_D);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_E);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_F);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_G);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_H);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_I);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_J);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_K);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_L);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_M);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_N);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_O);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_P);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_Q);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_R);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_S);
                     entries.add(ModBlocks.TROPICAL_FISH_BLOCK_T);
                     entries.add(ModBlocks.PRISMARINE_CRYSTAL_BLOCK);
                     entries.add(ModBlocks.GLOW_INK_SAC_BLOCK);
                     entries.add(ModBlocks.SCUTE_BLOCK);
                     entries.add(ModBlocks.FEATHER_BLOCK);
                     entries.add(ModBlocks.GHAST_TEAR_BLOCK);
                     entries.add(ModBlocks.PHANTOM_MEMBRANE_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_NETHER_WART_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_WARPED_WART_BLOCK);
                     entries.add(ModBlocks.MANGROVE_ROOTS_BLOCK);
                     entries.add(ModBlocks.VINE_BLOCK);
                     entries.add(ModBlocks.EGG_BLOCK);
                     entries.add(ModBlocks.PUFFERFISH_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_SPONGE);
                     entries.add(ModBlocks.COMPRESSED_BONE);
                     entries.add(ModBlocks.PAPER_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_SCAFFOLDING);
                     entries.add(ModBlocks.KELP_BLOCK);
                     entries.add(ModBlocks.LILY_PAD_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_GLOWSTONE);
                     entries.add(ModBlocks.COMPRESSED_RAW_IRON_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_RAW_GOLD_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_RAW_COPPER_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_IRON_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_REDSTONE_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_COAL_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_QUARTZ_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_NETHERITE_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_GOLD_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_DIAMOND_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_EMERALD_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_LAPIS_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_AMETHYST_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_COPPER_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_EXPOSED_COPPER);
                     entries.add(ModBlocks.COMPRESSED_WEATHERED_COPPER);
                     entries.add(ModBlocks.COMPRESSED_OXIDIZED_COPPER);
                     //entries.add(ModBlocks.COMPRESSED_CHERRY_LEAVES);
                     entries.add(ModBlocks.COMPRESSED_CHERRY_LOG);
                     entries.add(ModBlocks.COMPRESSED_CHERRY_SAPLING);
                     entries.add(ModBlocks.ENDER_EYE_BLOCK);
                     entries.add(ModBlocks.ENDER_PEARL_BLOCK);
                     entries.add(ModBlocks.ECHO_SHARD_BLOCK);
                     entries.add(ModBlocks.DENSE_COBWEB_BLOCK);
                     entries.add(ModBlocks.RABBIT_HIDE_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_COBBLED_DEEPSLATE);
                     entries.add(ModBlocks.SUPER_COMPRESSED_COBBLED_DEEPSLATE);
                     entries.add(ModBlocks.CARROT_BLOCK);
                     entries.add(ModBlocks.GOLDEN_CARROT_BLOCK);
                     entries.add(ModBlocks.APPLE_BLOCK);
                     entries.add(ModBlocks.GOLDEN_APPLE_BLOCK);
                     entries.add(ModBlocks.POTATO_BLOCK);
                     entries.add(ModBlocks.POISONOUS_POTATO_BLOCK);
                     entries.add(ModBlocks.BAKED_POTATO_BLOCK);
                     entries.add(ModBlocks.BEETROOT_BLOCK);
                     entries.add(ModBlocks.FLINT_BLOCK);
                     entries.add(ModBlocks.WAXED_COMPRESSED_COPPER_BLOCK);
                     entries.add(ModBlocks.WAXED_COMPRESSED_EXPOSED_COPPER);
                     entries.add(ModBlocks.WAXED_COMPRESSED_WEATHERED_COPPER);
                     entries.add(ModBlocks.WAXED_COMPRESSED_OXIDIZED_COPPER);
                     entries.add(ModBlocks.SUGAR_BLOCK);
                     entries.add(ModBlocks.GUNPOWDER_BLOCK);
                     entries.add(ModBlocks.COMPRESSED_PRISMARINE);
                    }).build());

    /*
    public static final ItemGroup SQUASHED_BLOCKS = FabricItemGroup.builder(new Identifier(Super.MOD_ID))
            .displayName(Text.literal("Squashed Blocks"))
            .icon(() -> new ItemStack(ModBlocks.COMPRESSED_STONE))
            .build();
    public static final ItemGroup SQUASHED_COLORED_BLOCKS = FabricItemGroup.builder(new Identifier(Super.MOD_ID))
            .displayName(Text.literal("Squashed Natural Blocks"))
            .icon(() -> new ItemStack(ModBlocks.COMPRESSED_STONE))
            .build();
    public static final ItemGroup SQUASHED_COMPRESSED = FabricItemGroup.builder(new Identifier(Super.MOD_ID))
            .displayName(Text.literal("Squashed Compressed Blocks"))
            .icon(() -> new ItemStack(ModBlocks.COMPRESSED_STONE))
            .build();
    */
}
