package net.leafenzo.squashed.datageneration;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.leafenzo.squashed.Super;
import net.leafenzo.squashed.block.ModBlocks;
import net.minecraft.data.client.BlockStateModelGenerator;
import net.minecraft.data.client.ItemModelGenerator;
import net.minecraft.data.client.TexturedModel;

public class ModModelProvider extends FabricModelProvider {
    public ModModelProvider(FabricDataOutput output) {
        super(output);
    }
    @Override
    public void generateBlockStateModels(BlockStateModelGenerator blockStateModelGenerator) {
        // Block Models
        blockStateModelGenerator.registerAxisRotated(ModBlocks.BLAZE_ROD_BLOCK, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.INK_SAC_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.STICK_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.FIRE_CHARGE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.MAGMA_CREAM_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.BLAZE_POWDER_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.RAW_SALMON_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COOKED_SALMON_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.RAW_COD_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COOKED_COD_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.RAW_RABBIT_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COOKED_RABBIT_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.RAW_MUTTON_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COOKED_MUTTON_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.RAW_CHICKEN_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COOKED_CHICKEN_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.RAW_BEEF_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COOKED_BEEF_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.RAW_PORK_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COOKED_PORK_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.ROTTEN_FLESH_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SPIDER_EYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.WHEAT_SEED_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.PUMPKIN_SEED_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.BEETROOT_SEED_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.MELON_SEED_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COCOA_BEAN_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.DEAD_BUSH_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.GLOW_BERRIES_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SWEET_BERRIES_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.GRASS_CLIPPINGS_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.FERN_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.GLOW_LICHEN_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.PUMPKIN_PILE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.HAY_PILE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.MELON_PILE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUGARCANE_BLOCK);

        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_SOUL_SAND);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_SOUL_SAND);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_COBBLESTONE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_COBBLESTONE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_STONE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_STONE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_ANDESITE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_ANDESITE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_GRAVEL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_GRAVEL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_TUFF);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_TUFF);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_BLACKSTONE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_BLACKSTONE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_OBSIDIAN);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_OBSIDIAN);
        //blockStateModelGenerator.registerSingleton(ModBlocks.COMPRESSED_DEEPSLATE, ?);
        //blockStateModelGenerator.registerSingleton(ModBlocks.SUPER_COMPRESSED_DEEPSLATE, ?);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_NETHERRACK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_NETHERRACK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_END_STONE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_END_STONE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_DIORITE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_DIORITE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_GRANITE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_GRANITE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_DIRT);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_DIRT);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_SAND);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_SAND);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_DRIPSTONE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_MARBLE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_MUD);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_MOSS);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_CLAY);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_RED_SAND);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SUPER_COMPRESSED_RED_SAND);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_MAGMA_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.WHITE_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.ORANGE_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.MAGENTA_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.LIGHT_BLUE_DYE_BLOCK );
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.YELLOW_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.LIME_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.PINK_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.GRAY_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.LIGHT_GRAY_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.CYAN_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.PURPLE_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.BLUE_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.BROWN_DYE_BLOCK );
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.GREEN_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.RED_DYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.BLACK_DYE_BLOCK);
        blockStateModelGenerator.registerSingleton(ModBlocks.COMPRESSED_BASALT, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.SUPER_COMPRESSED_BASALT, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.WHITE_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.ORANGE_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.MAGENTA_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.LIGHT_BLUE_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.YELLOW_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.LIME_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.PINK_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.GRAY_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.LIGHT_GRAY_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.CYAN_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.PURPLE_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.BLUE_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.BROWN_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.GREEN_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.RED_COMPRESSED_WOOL);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.BLACK_COMPRESSED_WOOL);
        blockStateModelGenerator.registerSingleton(ModBlocks.BOOK_BLOCK, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_OAK_LEAVES);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_SPRUCE_LEAVES);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_BIRCH_LEAVES);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_JUNGLE_LEAVES);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_ACACIA_LEAVES);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_DARK_OAK_LEAVES);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_MANGROVE_LEAVES);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_AZALEA_LEAVES);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_FLOWERING_AZALEA_LEAVES);
        blockStateModelGenerator.registerAxisRotated(ModBlocks.LEATHER_BLOCK, TexturedModel.CUBE_COLUMN);

        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_OAK_LOG);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_SPRUCE_LOG);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_BIRCH_LOG);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_JUNGLE_LOG);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_ACACIA_LOG);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_DARK_OAK_LOG);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_MANGROVE_LOG);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_CRIMSON_STEM);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_WARPED_STEM);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_BAMBOO);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_OAK_SAPLING);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_SPRUCE_SAPLING);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_BIRCH_SAPLING);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_JUNGLE_SAPLING);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_ACACIA_SAPLING);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_DARK_OAK_SAPLING);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_AZALEA_SAPLING);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_FLOWERING_AZALEA_MULCH);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_MANGROVE_PROPAGULE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_CRIMSON_MUSHROOM);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_WARPED_MUSHROOM);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.CHORUS_FRUIT_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_SEAGRASS);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_CACTUS);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_A);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_B);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_C);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_D);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_E);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_F);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_G);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_H);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_I);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_J);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_K);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_L);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_M);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_N);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_O);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_P);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_Q);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_R);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_S);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.TROPICAL_FISH_BLOCK_T);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.PRISMARINE_CRYSTAL_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.GLOW_INK_SAC);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SCUTE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.FEATHER_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.GHAST_TEAR_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.PHANTOM_MEMBRANE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_NETHER_WART_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_WARPED_WART_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.MANGROVE_ROOTS_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.VINE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.EGG_BLOCK);

        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_SPONGE);
        blockStateModelGenerator.registerAxisRotated(ModBlocks.COMPRESSED_BONE, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.PAPER_BLOCK, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerAxisRotated(ModBlocks.COMPRESSED_SCAFFOLDING, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.KELP_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.LILY_PAD_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_GLOWSTONE);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_RAW_IRON_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_RAW_GOLD_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_RAW_COPPER_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_IRON_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_REDSTONE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_COAL_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_QUARTZ_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_NETHERITE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_GOLD_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_DIAMOND_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_EMERALD_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_LAPIS_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_AMETHYST_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_COPPER_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_EXPOSED_COPPER);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_WEATHERED_COPPER);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_OXIDIZED_COPPER);
        // FOR:1.19.4
        // blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_CHERRY_LEAVES);
        // blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_CHERRY_LOG);
        // blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COMPRESSED_CHERRY_SAPLING);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.ENDER_EYE_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.ENDER_PEARL_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.ECHO_SHARD_BLOCK);
        blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.COBWEB_BLOCK);
        blockStateModelGenerator.registerAxisRotated(ModBlocks.RABBIT_HIDE_BLOCK, TexturedModel.CUBE_COLUMN);

        // BlockItem Models
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.BLAZE_ROD_BLOCK, Super.asResource("blaze_rod_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.INK_SAC_BLOCK, Super.asResource("ink_sac_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.STICK_BLOCK, Super.asResource("stick_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.FIRE_CHARGE_BLOCK, Super.asResource("fire_charge_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.MAGMA_CREAM_BLOCK, Super.asResource("magma_cream_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.BLAZE_POWDER_BLOCK, Super.asResource("blaze_powder_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.RAW_SALMON_BLOCK, Super.asResource("raw_salmon_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COOKED_SALMON_BLOCK, Super.asResource("cooked_salmon_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.RAW_COD_BLOCK, Super.asResource("raw_cod_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COOKED_COD_BLOCK, Super.asResource("cooked_cod_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.RAW_RABBIT_BLOCK, Super.asResource("raw_rabbit_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COOKED_RABBIT_BLOCK, Super.asResource("cooked_rabbit_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.RAW_MUTTON_BLOCK, Super.asResource("raw_mutton_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COOKED_MUTTON_BLOCK, Super.asResource("cooked_mutton_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.RAW_CHICKEN_BLOCK, Super.asResource("raw_chicken_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COOKED_CHICKEN_BLOCK, Super.asResource("cooked_chicken_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.RAW_BEEF_BLOCK, Super.asResource("raw_beef_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COOKED_BEEF_BLOCK, Super.asResource("cooked_beef_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.RAW_PORK_BLOCK, Super.asResource("raw_pork_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COOKED_PORK_BLOCK, Super.asResource("cooked_pork_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.ROTTEN_FLESH_BLOCK, Super.asResource("rotten_flesh_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SPIDER_EYE_BLOCK, Super.asResource("spider_eye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.WHEAT_SEED_BLOCK, Super.asResource("wheat_seed_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.PUMPKIN_SEED_BLOCK, Super.asResource("pumpkin_seed_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.BEETROOT_SEED_BLOCK, Super.asResource("beetroot_seed_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.MELON_SEED_BLOCK, Super.asResource("melon_seed_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COCOA_BEAN_BLOCK, Super.asResource("cocoa_bean_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.DEAD_BUSH_BLOCK, Super.asResource("dead_bush_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.GLOW_BERRIES_BLOCK, Super.asResource("glow_berries_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SWEET_BERRIES_BLOCK, Super.asResource("sweet_berries_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.GRASS_CLIPPINGS_BLOCK, Super.asResource("grass_clippings_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.FERN_BLOCK, Super.asResource("fern_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.GLOW_LICHEN_BLOCK, Super.asResource("glow_lichen_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.PUMPKIN_PILE, Super.asResource("pumpkin_pile"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.HAY_PILE, Super.asResource("hay_pile"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.MELON_PILE, Super.asResource("melon_pile"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUGARCANE_BLOCK, Super.asResource("sugarcane_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SEA_PICKLE_BLOCK, Super.asResource("sea_pickle_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_SOUL_SAND, Super.asResource("compressed_soul_sand"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_SOUL_SAND, Super.asResource("super_compressed_soul_sand"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_COBBLESTONE, Super.asResource("compressed_cobblestone"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_COBBLESTONE, Super.asResource("super_compressed_cobblestone"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_STONE, Super.asResource("compressed_stone"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_STONE, Super.asResource("super_compressed_stone"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_ANDESITE, Super.asResource("compressed_andesite"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_ANDESITE, Super.asResource("super_compressed_andesite"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_GRAVEL, Super.asResource("compressed_gravel"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_GRAVEL, Super.asResource("super_compressed_gravel"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_TUFF, Super.asResource("compressed_tuff"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_TUFF, Super.asResource("super_compressed_tuff"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_BLACKSTONE, Super.asResource("compressed_blackstone"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_BLACKSTONE, Super.asResource("super_compressed_blackstone"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_OBSIDIAN, Super.asResource("compressed_obsidian"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_OBSIDIAN, Super.asResource("super_compressed_obsidian"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_DEEPSLATE, Super.asResource("compressed_deepslate"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_DEEPSLATE, Super.asResource("super_compressed_deepslate"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_NETHERRACK, Super.asResource("compressed_netherrack"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_NETHERRACK, Super.asResource("super_compressed_netherrack"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_END_STONE, Super.asResource("compressed_end_stone"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_END_STONE, Super.asResource("super_compressed_end_stone"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_DIORITE, Super.asResource("compressed_diorite"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_DIORITE, Super.asResource("super_compressed_diorite"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_GRANITE, Super.asResource("compressed_granite"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_GRANITE, Super.asResource("super_compressed_granite"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_DIRT, Super.asResource("compressed_dirt"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_DIRT, Super.asResource("super_compressed_dirt"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_SAND, Super.asResource("compressed_sand"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_SAND, Super.asResource("super_compressed_sand"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_DRIPSTONE, Super.asResource("compressed_dripstone"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_MARBLE, Super.asResource("compressed_marble"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_MUD, Super.asResource("compressed_mud"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_MOSS, Super.asResource("compressed_moss"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_CLAY, Super.asResource("compressed_clay"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_RED_SAND, Super.asResource("compressed_red_sand"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_RED_SAND, Super.asResource("super_compressed_red_sand"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_MAGMA_BLOCK, Super.asResource("compressed_magma_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.WHITE_DYE_BLOCK, Super.asResource("white_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.ORANGE_DYE_BLOCK, Super.asResource("orange_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.MAGENTA_DYE_BLOCK, Super.asResource("magenta_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.LIGHT_BLUE_DYE_BLOCK , Super.asResource("light_blue_dye_block "));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.YELLOW_DYE_BLOCK, Super.asResource("yellow_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.LIME_DYE_BLOCK, Super.asResource("lime_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.PINK_DYE_BLOCK, Super.asResource("pink_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.GRAY_DYE_BLOCK, Super.asResource("gray_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.LIGHT_GRAY_DYE_BLOCK, Super.asResource("light_gray_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.CYAN_DYE_BLOCK, Super.asResource("cyan_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.PURPLE_DYE_BLOCK, Super.asResource("purple_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.BLUE_DYE_BLOCK, Super.asResource("blue_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.BROWN_DYE_BLOCK , Super.asResource("brown_dye_block "));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.GREEN_DYE_BLOCK, Super.asResource("green_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.RED_DYE_BLOCK, Super.asResource("red_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.BLACK_DYE_BLOCK, Super.asResource("black_dye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_BASALT, Super.asResource("compressed_basalt"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SUPER_COMPRESSED_BASALT, Super.asResource("super_compressed_basalt"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.WHITE_COMPRESSED_WOOL, Super.asResource("white_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.ORANGE_COMPRESSED_WOOL, Super.asResource("orange_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.MAGENTA_COMPRESSED_WOOL, Super.asResource("magenta_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.LIGHT_BLUE_COMPRESSED_WOOL, Super.asResource("light_blue_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.YELLOW_COMPRESSED_WOOL, Super.asResource("yellow_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.LIME_COMPRESSED_WOOL, Super.asResource("lime_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.PINK_COMPRESSED_WOOL, Super.asResource("pink_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.GRAY_COMPRESSED_WOOL, Super.asResource("gray_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.LIGHT_GRAY_COMPRESSED_WOOL, Super.asResource("light_gray_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.CYAN_COMPRESSED_WOOL, Super.asResource("cyan_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.PURPLE_COMPRESSED_WOOL, Super.asResource("purple_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.BLUE_COMPRESSED_WOOL, Super.asResource("blue_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.BROWN_COMPRESSED_WOOL, Super.asResource("brown_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.GREEN_COMPRESSED_WOOL, Super.asResource("green_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.RED_COMPRESSED_WOOL, Super.asResource("red_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.BLACK_COMPRESSED_WOOL, Super.asResource("black_compressed_wool"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.BOOK_BLOCK, Super.asResource("book_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_OAK_LEAVES, Super.asResource("compressed_oak_leaves"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_SPRUCE_LEAVES, Super.asResource("compressed_spruce_leaves"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_BIRCH_LEAVES, Super.asResource("compressed_birch_leaves"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_JUNGLE_LEAVES, Super.asResource("compressed_jungle_leaves"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_ACACIA_LEAVES, Super.asResource("compressed_acacia_leaves"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_DARK_OAK_LEAVES, Super.asResource("compressed_dark_oak_leaves"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_MANGROVE_LEAVES, Super.asResource("compressed_mangrove_leaves"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_AZALEA_LEAVES, Super.asResource("compressed_azalea_leaves"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_FLOWERING_AZALEA_LEAVES, Super.asResource("compressed_flowering_azalea_leaves"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.LEATHER_BLOCK, Super.asResource("leather_block"));
        //blockStateModelGenerator.registerParentedItemModel(ModBlocks.CHOIR_BLOCK, Super.asResource("choir_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_OAK_LOG, Super.asResource("compressed_oak_log"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_SPRUCE_LOG, Super.asResource("compressed_spruce_log"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_BIRCH_LOG, Super.asResource("compressed_birch_log"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_JUNGLE_LOG, Super.asResource("compressed_jungle_log"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_ACACIA_LOG, Super.asResource("compressed_acacia_log"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_DARK_OAK_LOG, Super.asResource("compressed_dark_oak_log"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_MANGROVE_LOG, Super.asResource("compressed_mangrove_log"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_CRIMSON_STEM, Super.asResource("compressed_crimson_stem"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_WARPED_STEM, Super.asResource("compressed_warped_stem"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_BAMBOO, Super.asResource("compressed_bamboo"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_OAK_SAPLING, Super.asResource("compressed_oak_sapling"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_SPRUCE_SAPLING, Super.asResource("compressed_spruce_sapling"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_BIRCH_SAPLING, Super.asResource("compressed_birch_sapling"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_JUNGLE_SAPLING, Super.asResource("compressed_jungle_sapling"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_ACACIA_SAPLING, Super.asResource("compressed_acacia_sapling"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_DARK_OAK_SAPLING, Super.asResource("compressed_dark_oak_sapling"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_AZALEA_SAPLING, Super.asResource("compressed_azalea_sapling"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_FLOWERING_AZALEA_MULCH, Super.asResource("compressed_flowering_azalea_mulch"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_MANGROVE_PROPAGULE, Super.asResource("compressed_mangrove_propagule"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_CRIMSON_MUSHROOM, Super.asResource("compressed_crimson_mushroom"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_WARPED_MUSHROOM, Super.asResource("compressed_warped_mushroom"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.CHORUS_FRUIT_BLOCK, Super.asResource("chorus_fruit_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_SEAGRASS, Super.asResource("compressed_seagrass"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_CACTUS, Super.asResource("compressed_cactus"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_A, Super.asResource("tropical_fish_block_a")); //TODO Finish & Implement Tropical Fish BlockItem Instead
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_B, Super.asResource("tropical_fish_block_b"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_C, Super.asResource("tropical_fish_block_c"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_D, Super.asResource("tropical_fish_block_d"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_E, Super.asResource("tropical_fish_block_e"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_F, Super.asResource("tropical_fish_block_f"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_G, Super.asResource("tropical_fish_block_g"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_H, Super.asResource("tropical_fish_block_h"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_I, Super.asResource("tropical_fish_block_i"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_J, Super.asResource("tropical_fish_block_j"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_K, Super.asResource("tropical_fish_block_k"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_L, Super.asResource("tropical_fish_block_l"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_M, Super.asResource("tropical_fish_block_m"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_N, Super.asResource("tropical_fish_block_n"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_O, Super.asResource("tropical_fish_block_o"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_P, Super.asResource("tropical_fish_block_p"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_Q, Super.asResource("tropical_fish_block_q"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_R, Super.asResource("tropical_fish_block_r"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_S, Super.asResource("tropical_fish_block_s"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.TROPICAL_FISH_BLOCK_T, Super.asResource("tropical_fish_block_t"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.PRISMARINE_CRYSTAL_BLOCK, Super.asResource("prismarine_crystal_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.GLOW_INK_SAC, Super.asResource("glow_ink_sac"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.SCUTE_BLOCK, Super.asResource("scute_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.FEATHER_BLOCK, Super.asResource("feather_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.GHAST_TEAR_BLOCK, Super.asResource("ghast_tear_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.PHANTOM_MEMBRANE_BLOCK, Super.asResource("phantom_membrane_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_NETHER_WART_BLOCK, Super.asResource("compressed_nether_wart_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_WARPED_WART_BLOCK, Super.asResource("compressed_warped_wart_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.MANGROVE_ROOTS_BLOCK, Super.asResource("mangrove_roots_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.VINE_BLOCK, Super.asResource("vine_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.EGG_BLOCK, Super.asResource("egg_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.PUFFERFISH_BLOCK, Super.asResource("pufferfish_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_SPONGE, Super.asResource("compressed_sponge"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_BONE, Super.asResource("compressed_bone"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.PAPER_BLOCK, Super.asResource("paper_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_SCAFFOLDING, Super.asResource("compressed_scaffolding"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.KELP_BLOCK, Super.asResource("kelp_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.LILY_PAD_BLOCK, Super.asResource("lily_pad_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_GLOWSTONE, Super.asResource("compressed_glowstone"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_RAW_IRON_BLOCK, Super.asResource("compressed_raw_iron_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_RAW_GOLD_BLOCK, Super.asResource("compressed_raw_gold_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_RAW_COPPER_BLOCK, Super.asResource("compressed_raw_copper_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_IRON_BLOCK, Super.asResource("compressed_iron_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_REDSTONE_BLOCK, Super.asResource("compressed_redstone_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_COAL_BLOCK, Super.asResource("compressed_coal_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_QUARTZ_BLOCK, Super.asResource("compressed_quartz_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_NETHERITE_BLOCK, Super.asResource("compressed_netherite_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_GOLD_BLOCK, Super.asResource("compressed_gold_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_DIAMOND_BLOCK, Super.asResource("compressed_diamond_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_EMERALD_BLOCK, Super.asResource("compressed_emerald_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_LAPIS_BLOCK, Super.asResource("compressed_lapis_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_AMETHYST_BLOCK, Super.asResource("compressed_amethyst_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_COPPER_BLOCK, Super.asResource("compressed_copper_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_EXPOSED_COPPER, Super.asResource("compressed_exposed_copper"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_WEATHERED_COPPER, Super.asResource("compressed_weathered_copper"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_OXIDIZED_COPPER, Super.asResource("compressed_oxidized_copper"));
        // FOR:1.19.4
        // blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_CHERRY_LEAVES, Super.asResource("compressed_cherry_leaves"));
        // blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_CHERRY_LOG, Super.asResource("compressed_cherry_log"));
        // blockStateModelGenerator.registerParentedItemModel(ModBlocks.COMPRESSED_CHERRY_SAPLING, Super.asResource("compressed_cherry_sapling"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.ENDER_EYE_BLOCK, Super.asResource("ender_eye_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.ENDER_PEARL_BLOCK, Super.asResource("ender_pearl_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.ECHO_SHARD_BLOCK, Super.asResource("echo_shard_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.COBWEB_BLOCK, Super.asResource("cobweb_block"));
        blockStateModelGenerator.registerParentedItemModel(ModBlocks.RABBIT_HIDE_BLOCK, Super.asResource("rabbit_hide_block"));
    }
    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {

    }
}