package net.leafenzo.squashed.datageneration;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider;
import net.leafenzo.squashed.block.ModBlocks;
import net.minecraft.data.server.recipe.RecipeJsonProvider;
import net.minecraft.data.server.recipe.ShapelessRecipeJsonBuilder;
import net.minecraft.item.ItemConvertible;
import net.minecraft.item.Items;
import net.minecraft.recipe.book.RecipeCategory;

import java.util.function.Consumer;


public class ModRecipeProvider extends FabricRecipeProvider {
    public ModRecipeProvider(FabricDataOutput output) { super(output); }

    public static void offerCompressedWoolDyeingRecipe(Consumer<RecipeJsonProvider> exporter, ItemConvertible output, ItemConvertible input) {
        ShapelessRecipeJsonBuilder.create(RecipeCategory.BUILDING_BLOCKS, output).input(input).input(ModBlocks.WHITE_COMPRESSED_WOOL).group("wool").criterion(FabricRecipeProvider.hasItem(ModBlocks.WHITE_COMPRESSED_WOOL), FabricRecipeProvider.conditionsFromItem(ModBlocks.WHITE_COMPRESSED_WOOL)).offerTo(exporter);
    }

    @Override
    public void generate(Consumer<RecipeJsonProvider> exporter) {
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BLAZE_ROD, RecipeCategory.MISC, ModBlocks.BLAZE_ROD_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.INK_SAC, RecipeCategory.MISC, ModBlocks.INK_SAC_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.STICK, RecipeCategory.MISC, ModBlocks.STICK_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.FIRE_CHARGE, RecipeCategory.MISC, ModBlocks.FIRE_CHARGE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MAGMA_CREAM, RecipeCategory.MISC, ModBlocks.MAGMA_CREAM_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BLAZE_POWDER, RecipeCategory.MISC, ModBlocks.BLAZE_POWDER_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SALMON, RecipeCategory.MISC, ModBlocks.RAW_SALMON_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COOKED_SALMON, RecipeCategory.MISC, ModBlocks.COOKED_SALMON_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COD, RecipeCategory.MISC, ModBlocks.RAW_COD_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COOKED_COD, RecipeCategory.MISC, ModBlocks.COOKED_COD_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.RABBIT, RecipeCategory.MISC, ModBlocks.RAW_RABBIT_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COOKED_RABBIT, RecipeCategory.MISC, ModBlocks.COOKED_RABBIT_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MUTTON, RecipeCategory.MISC, ModBlocks.RAW_MUTTON_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COOKED_MUTTON, RecipeCategory.MISC, ModBlocks.COOKED_MUTTON_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.CHICKEN, RecipeCategory.MISC, ModBlocks.RAW_CHICKEN_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COOKED_CHICKEN, RecipeCategory.MISC, ModBlocks.COOKED_CHICKEN_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BEEF, RecipeCategory.MISC, ModBlocks.RAW_BEEF_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COOKED_BEEF, RecipeCategory.MISC, ModBlocks.COOKED_BEEF_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.PORKCHOP, RecipeCategory.MISC, ModBlocks.RAW_PORK_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COOKED_PORKCHOP, RecipeCategory.MISC, ModBlocks.COOKED_PORK_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.ROTTEN_FLESH, RecipeCategory.MISC, ModBlocks.ROTTEN_FLESH_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SPIDER_EYE, RecipeCategory.MISC, ModBlocks.SPIDER_EYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.WHEAT_SEEDS, RecipeCategory.MISC, ModBlocks.WHEAT_SEED_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.PUMPKIN_SEEDS, RecipeCategory.MISC, ModBlocks.PUMPKIN_SEED_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BEETROOT_SEEDS, RecipeCategory.MISC, ModBlocks.BEETROOT_SEED_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MELON_SEEDS, RecipeCategory.MISC, ModBlocks.MELON_SEED_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COCOA_BEANS, RecipeCategory.MISC, ModBlocks.COCOA_BEAN_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.DEAD_BUSH, RecipeCategory.MISC, ModBlocks.DEAD_BUSH_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GLOW_BERRIES, RecipeCategory.MISC, ModBlocks.GLOW_BERRIES_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SWEET_BERRIES, RecipeCategory.MISC, ModBlocks.SWEET_BERRIES_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.FERN, RecipeCategory.MISC, ModBlocks.FERN_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GLOW_LICHEN, RecipeCategory.MISC, ModBlocks.GLOW_LICHEN_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.PUMPKIN, RecipeCategory.MISC, ModBlocks.PUMPKIN_PILE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.HAY_BLOCK, RecipeCategory.MISC, ModBlocks.HAY_PILE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MELON, RecipeCategory.MISC, ModBlocks.MELON_PILE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SUGAR_CANE, RecipeCategory.MISC, ModBlocks.SUGARCANE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SEA_PICKLE, RecipeCategory.MISC, ModBlocks.SEA_PICKLE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SOUL_SAND, RecipeCategory.MISC, ModBlocks.COMPRESSED_SOUL_SAND);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_SOUL_SAND, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_SOUL_SAND);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COBBLESTONE, RecipeCategory.MISC, ModBlocks.COMPRESSED_COBBLESTONE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_COBBLESTONE, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_COBBLESTONE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.STONE, RecipeCategory.MISC, ModBlocks.COMPRESSED_STONE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_STONE, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_STONE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.ANDESITE, RecipeCategory.MISC, ModBlocks.COMPRESSED_ANDESITE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_ANDESITE, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_ANDESITE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GRAVEL, RecipeCategory.MISC, ModBlocks.COMPRESSED_GRAVEL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_GRAVEL, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_GRAVEL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.TUFF, RecipeCategory.MISC, ModBlocks.COMPRESSED_TUFF);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_SOUL_SAND, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_TUFF);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BLACKSTONE, RecipeCategory.MISC, ModBlocks.COMPRESSED_BLACKSTONE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_BLACKSTONE, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_BLACKSTONE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.OBSIDIAN, RecipeCategory.MISC, ModBlocks.COMPRESSED_OBSIDIAN);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_OBSIDIAN, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_OBSIDIAN);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.DEEPSLATE, RecipeCategory.MISC, ModBlocks.COMPRESSED_DEEPSLATE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_DEEPSLATE, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_DEEPSLATE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.NETHERRACK, RecipeCategory.MISC, ModBlocks.COMPRESSED_NETHERRACK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_NETHERRACK, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_NETHERRACK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.END_STONE, RecipeCategory.MISC, ModBlocks.COMPRESSED_END_STONE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_END_STONE, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_END_STONE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.DIORITE, RecipeCategory.MISC, ModBlocks.COMPRESSED_DIORITE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_DIORITE, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_DIORITE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GRANITE, RecipeCategory.MISC, ModBlocks.COMPRESSED_GRANITE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_GRANITE, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_GRANITE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.DIRT, RecipeCategory.MISC, ModBlocks.COMPRESSED_DIRT);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_DIRT, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_DIRT);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SAND, RecipeCategory.MISC, ModBlocks.COMPRESSED_SAND);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_SAND, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_SAND);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.DRIPSTONE_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_DRIPSTONE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.CALCITE, RecipeCategory.MISC, ModBlocks.COMPRESSED_CALCITE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MUD, RecipeCategory.MISC, ModBlocks.COMPRESSED_MUD);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MOSS_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_MOSS);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.CLAY, RecipeCategory.MISC, ModBlocks.COMPRESSED_CLAY);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.RED_SAND, RecipeCategory.MISC, ModBlocks.COMPRESSED_RED_SAND);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_RED_SAND, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_RED_SAND);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MAGMA_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_MAGMA_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.WHITE_DYE, RecipeCategory.MISC, ModBlocks.WHITE_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.ORANGE_DYE, RecipeCategory.MISC, ModBlocks.ORANGE_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MAGENTA_DYE, RecipeCategory.MISC, ModBlocks.MAGENTA_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.LIGHT_BLUE_DYE, RecipeCategory.MISC, ModBlocks.LIGHT_BLUE_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.YELLOW_DYE, RecipeCategory.MISC, ModBlocks.YELLOW_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.LIME_DYE, RecipeCategory.MISC, ModBlocks.LIME_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.PINK_DYE, RecipeCategory.MISC, ModBlocks.PINK_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GRAY_DYE, RecipeCategory.MISC, ModBlocks.GRAY_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.LIGHT_GRAY_DYE, RecipeCategory.MISC, ModBlocks.LIGHT_GRAY_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.CYAN_DYE, RecipeCategory.MISC, ModBlocks.CYAN_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.PURPLE_DYE, RecipeCategory.MISC, ModBlocks.PURPLE_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BLUE_DYE, RecipeCategory.MISC, ModBlocks.BLUE_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BROWN_DYE, RecipeCategory.MISC, ModBlocks.BROWN_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GREEN_DYE, RecipeCategory.MISC, ModBlocks.GREEN_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.RED_DYE, RecipeCategory.MISC, ModBlocks.RED_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BLACK_DYE, RecipeCategory.MISC, ModBlocks.BLACK_DYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BASALT, RecipeCategory.MISC, ModBlocks.COMPRESSED_BASALT);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_BASALT, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_BASALT);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.WHITE_WOOL, RecipeCategory.MISC, ModBlocks.WHITE_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.ORANGE_WOOL, RecipeCategory.MISC, ModBlocks.ORANGE_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MAGENTA_WOOL, RecipeCategory.MISC, ModBlocks.MAGENTA_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.LIGHT_BLUE_WOOL, RecipeCategory.MISC, ModBlocks.LIGHT_BLUE_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.YELLOW_WOOL, RecipeCategory.MISC, ModBlocks.YELLOW_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.LIME_WOOL, RecipeCategory.MISC, ModBlocks.LIME_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.PINK_WOOL, RecipeCategory.MISC, ModBlocks.PINK_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GRAY_WOOL, RecipeCategory.MISC, ModBlocks.GRAY_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.LIGHT_GRAY_WOOL, RecipeCategory.MISC, ModBlocks.LIGHT_GRAY_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.CYAN_WOOL, RecipeCategory.MISC, ModBlocks.CYAN_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.PURPLE_WOOL, RecipeCategory.MISC, ModBlocks.PURPLE_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BLUE_WOOL, RecipeCategory.MISC, ModBlocks.BLUE_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BROWN_WOOL, RecipeCategory.MISC, ModBlocks.BROWN_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GREEN_WOOL, RecipeCategory.MISC, ModBlocks.GREEN_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.RED_WOOL, RecipeCategory.MISC, ModBlocks.RED_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BLACK_WOOL, RecipeCategory.MISC, ModBlocks.BLACK_COMPRESSED_WOOL);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BOOK, RecipeCategory.MISC, ModBlocks.BOOK_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.OAK_LEAVES, RecipeCategory.MISC, ModBlocks.COMPRESSED_OAK_LEAVES);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SPRUCE_LEAVES, RecipeCategory.MISC, ModBlocks.COMPRESSED_SPRUCE_LEAVES);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BIRCH_LEAVES, RecipeCategory.MISC, ModBlocks.COMPRESSED_BIRCH_LEAVES);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.JUNGLE_LEAVES, RecipeCategory.MISC, ModBlocks.COMPRESSED_JUNGLE_LEAVES);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.ACACIA_LEAVES, RecipeCategory.MISC, ModBlocks.COMPRESSED_ACACIA_LEAVES);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.DARK_OAK_LEAVES, RecipeCategory.MISC, ModBlocks.COMPRESSED_DARK_OAK_LEAVES);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MANGROVE_LEAVES, RecipeCategory.MISC, ModBlocks.COMPRESSED_MANGROVE_LEAVES);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.AZALEA_LEAVES, RecipeCategory.MISC, ModBlocks.COMPRESSED_AZALEA_LEAVES);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.FLOWERING_AZALEA_LEAVES, RecipeCategory.MISC, ModBlocks.COMPRESSED_FLOWERING_AZALEA_LEAVES);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.LEATHER, RecipeCategory.MISC, ModBlocks.LEATHER_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.OAK_LOG, RecipeCategory.MISC, ModBlocks.COMPRESSED_OAK_LOG);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SPRUCE_LOG, RecipeCategory.MISC, ModBlocks.COMPRESSED_SPRUCE_LOG);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BIRCH_LOG, RecipeCategory.MISC, ModBlocks.COMPRESSED_BIRCH_LOG);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.JUNGLE_LOG, RecipeCategory.MISC, ModBlocks.COMPRESSED_JUNGLE_LOG);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.ACACIA_LOG, RecipeCategory.MISC, ModBlocks.COMPRESSED_ACACIA_LOG);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.DARK_OAK_LOG, RecipeCategory.MISC, ModBlocks.COMPRESSED_DARK_OAK_LOG);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MANGROVE_LOG, RecipeCategory.MISC, ModBlocks.COMPRESSED_MANGROVE_LOG);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.CRIMSON_STEM, RecipeCategory.MISC, ModBlocks.COMPRESSED_CRIMSON_STEM);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.WARPED_STEM, RecipeCategory.MISC, ModBlocks.COMPRESSED_WARPED_STEM);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BAMBOO_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_BAMBOO);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.OAK_SAPLING, RecipeCategory.MISC, ModBlocks.COMPRESSED_OAK_SAPLING);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SPRUCE_SAPLING, RecipeCategory.MISC, ModBlocks.COMPRESSED_SPRUCE_SAPLING);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BIRCH_SAPLING, RecipeCategory.MISC, ModBlocks.COMPRESSED_BIRCH_SAPLING);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.JUNGLE_SAPLING, RecipeCategory.MISC, ModBlocks.COMPRESSED_JUNGLE_SAPLING);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.ACACIA_SAPLING, RecipeCategory.MISC, ModBlocks.COMPRESSED_ACACIA_SAPLING);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.DARK_OAK_SAPLING, RecipeCategory.MISC, ModBlocks.COMPRESSED_DARK_OAK_SAPLING);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.AZALEA, RecipeCategory.MISC, ModBlocks.COMPRESSED_AZALEA_SAPLING);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.FLOWERING_AZALEA, RecipeCategory.MISC, ModBlocks.COMPRESSED_FLOWERING_AZALEA_SAPLING);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MANGROVE_PROPAGULE, RecipeCategory.MISC, ModBlocks.COMPRESSED_MANGROVE_PROPAGULE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.CRIMSON_FUNGUS, RecipeCategory.MISC, ModBlocks.COMPRESSED_CRIMSON_FUNGUS);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.WARPED_FUNGUS, RecipeCategory.MISC, ModBlocks.COMPRESSED_WARPED_FUNGUS);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.CHORUS_FRUIT, RecipeCategory.MISC, ModBlocks.CHORUS_FRUIT_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SEAGRASS, RecipeCategory.MISC, ModBlocks.COMPRESSED_SEAGRASS);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.CACTUS, RecipeCategory.MISC, ModBlocks.COMPRESSED_CACTUS);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.PRISMARINE_SHARD, RecipeCategory.MISC, ModBlocks.PRISMARINE_CRYSTAL_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GLOW_INK_SAC, RecipeCategory.MISC, ModBlocks.GLOW_INK_SAC_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SCUTE, RecipeCategory.MISC, ModBlocks.SCUTE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.FEATHER, RecipeCategory.MISC, ModBlocks.FEATHER_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GHAST_TEAR, RecipeCategory.MISC, ModBlocks.GHAST_TEAR_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.PHANTOM_MEMBRANE, RecipeCategory.MISC, ModBlocks.PHANTOM_MEMBRANE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.NETHER_WART_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_NETHER_WART_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.WARPED_WART_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_WARPED_WART_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.MANGROVE_ROOTS, RecipeCategory.MISC, ModBlocks.MANGROVE_ROOTS_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.VINE, RecipeCategory.MISC, ModBlocks.VINE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.EGG, RecipeCategory.MISC, ModBlocks.EGG_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BONE, RecipeCategory.MISC, ModBlocks.COMPRESSED_BONE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.PAPER, RecipeCategory.MISC, ModBlocks.PAPER_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.SCAFFOLDING, RecipeCategory.MISC, ModBlocks.COMPRESSED_SCAFFOLDING);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.KELP, RecipeCategory.MISC, ModBlocks.KELP_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GLOWSTONE, RecipeCategory.MISC, ModBlocks.COMPRESSED_GLOWSTONE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.RAW_IRON, RecipeCategory.MISC, ModBlocks.COMPRESSED_RAW_IRON_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.RAW_GOLD, RecipeCategory.MISC, ModBlocks.COMPRESSED_RAW_GOLD_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.RAW_COPPER, RecipeCategory.MISC, ModBlocks.COMPRESSED_RAW_COPPER_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.IRON_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_IRON_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.REDSTONE_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_REDSTONE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COAL_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_COAL_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.QUARTZ_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_QUARTZ_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.NETHERITE_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_NETHERITE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GOLD_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_GOLD_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.DIAMOND_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_DIAMOND_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.EMERALD_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_EMERALD_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.LAPIS_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_LAPIS_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.AMETHYST_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_AMETHYST_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COPPER_BLOCK, RecipeCategory.MISC, ModBlocks.COMPRESSED_COPPER_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.EXPOSED_COPPER, RecipeCategory.MISC, ModBlocks.COMPRESSED_EXPOSED_COPPER);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.WEATHERED_COPPER, RecipeCategory.MISC, ModBlocks.COMPRESSED_WEATHERED_COPPER);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.OXIDIZED_COPPER, RecipeCategory.MISC, ModBlocks.COMPRESSED_OXIDIZED_COPPER);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.ENDER_EYE, RecipeCategory.MISC, ModBlocks.ENDER_EYE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.ENDER_PEARL, RecipeCategory.MISC, ModBlocks.ENDER_PEARL_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.ECHO_SHARD, RecipeCategory.MISC, ModBlocks.ECHO_SHARD_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COBWEB, RecipeCategory.MISC, ModBlocks.DENSE_COBWEB_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.RABBIT_HIDE, RecipeCategory.MISC, ModBlocks.RABBIT_HIDE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.COBBLED_DEEPSLATE, RecipeCategory.MISC, ModBlocks.COMPRESSED_COBBLED_DEEPSLATE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, ModBlocks.COMPRESSED_COBBLED_DEEPSLATE, RecipeCategory.MISC, ModBlocks.SUPER_COMPRESSED_COBBLED_DEEPSLATE);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.CARROT, RecipeCategory.MISC, ModBlocks.CARROT_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GOLDEN_CARROT, RecipeCategory.MISC, ModBlocks.GOLDEN_CARROT_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.APPLE, RecipeCategory.MISC, ModBlocks.APPLE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.GOLDEN_APPLE, RecipeCategory.MISC, ModBlocks.GOLDEN_APPLE_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.POTATO, RecipeCategory.MISC, ModBlocks.POTATO_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.POISONOUS_POTATO, RecipeCategory.MISC, ModBlocks.POISONOUS_POTATO_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BAKED_POTATO, RecipeCategory.MISC, ModBlocks.BAKED_POTATO_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.BEETROOT, RecipeCategory.MISC, ModBlocks.BEETROOT_BLOCK);
        offerReversibleCompactingRecipes(exporter, RecipeCategory.BUILDING_BLOCKS, Items.FLINT, RecipeCategory.MISC, ModBlocks.FLINT_BLOCK);

        //offerWoolDyeingRecipe(exporter, ModBlocks.ORANGE_COMPRESSED_WOOL, ModBlocks.ORANGE_DYE_BLOCK, RecipeCategory.BUILDING_BLOCKS);
          //offerSingleOutputShapelessRecipe(exporter, Items.ORANGE_WOOL, Items.CYAN_WOOL, RecipeCategory.MISC);

          //offerCompressedWoolDyeingRecipe(exporter, ModBlocks.);
    }


}
